{{ if .setup_gnome -}}
".local/bin/gnome-shell-extension-installer":
    type: file
    url: "https://github.com/brunelli/gnome-shell-extension-installer/raw/master/gnome-shell-extension-installer"
    executable: true
{{ end }}

".antigen/antigen.zsh":
    type: file
    url: "https://git.io/antigen"
