{{ if .setup_gnome -}}
".local/bin/gnome-shell-extension-installer":
    type: file
    url: "https://github.com/brunelli/gnome-shell-extension-installer/raw/master/gnome-shell-extension-installer"
    executable: true

### --> Tiling-like configuration
".local/share/fonts/cantarell-nerd-fonts-complete":
    type: archive
    url: "https://github.com/s373r/cantarell-nerd-font/archive/main.tar.gz"
    stripComponents: 1
    include: ["*/*.otf"]
### <-- Tiling-like configuration
{{ end }}

".antigen/antigen.zsh":
    type: file
    url: "https://git.io/antigen"

".config/tmux/plugins/tpm":
    type: git-repo
    url: "https://github.com/tmux-plugins/tpm"
