{{ if .setup_gnome -}}
".local/bin/gnome-shell-extension-installer":
    type: file
    url: "https://github.com/brunelli/gnome-shell-extension-installer/raw/master/gnome-shell-extension-installer"
    executable: true

# NOTE(DP): disabled
".local/share/gnome-shell/extensions/steal-my-focus@kagesenshi.org":
    type: archive
    url: "https://github.com/s373r/gnome-shell-extension-stealmyfocus/archive/master.tar.gz"
    stripComponents: 1

".local/share/gnome-shell/extensions/gnome-shell-go-to-last-workspace@github.com":
    type: archive
    url: "https://github.com/arjan/gnome-shell-go-to-last-workspace/archive/master.tar.gz"
    stripComponents: 1
{{ end }}

".antigen/antigen.zsh":
    type: file
    url: "https://git.io/antigen"
