# NOTE: based on
#       https://gitlab.com/dwt1/dotfiles/-/blob/master/.config/alacritty/alacritty.yml
# TODO: hotkeys

[font]
size = 20.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.85

[window.padding]
x = 16
y = 16

[mouse]
hide_when_typing = true

bindings = [
    { mouse = "Right", action = "Paste" },
]

[keyboard]
bindings = [
    { key = "ะก", mods = "Control|Shift", action = "Copy" },
    { key = "ะ", mods = "Control|Shift", action = "Paste" }
]

[selection]
save_to_clipboard = true
